# Generated by Django 4.0.1 on 2022-03-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABcollegE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='postinternship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='pics')),
                ('salary', models.IntegerField()),
                ('duration', models.DurationField()),
                ('eligiblity', models.CharField(max_length=800)),
                ('isvacant', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='destination',
        ),
    ]
