# Generated by Django 4.0.1 on 2022-03-06 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ABcollegE', '0002_internship_postinternship_delete_destination'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='internship',
            new_name='destination',
        ),
    ]
