# Generated by Django 4.0.1 on 2022-03-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABcollegE', '0003_rename_internship_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='pics')),
                ('link', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('eligiblity', models.CharField(max_length=400)),
            ],
        ),
    ]
