# Generated by Django 4.0.1 on 2022-03-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABcollegE', '0004_scholarship'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='pics')),
                ('link', models.CharField(max_length=200)),
                ('time', models.DurationField()),
                ('venue', models.CharField(max_length=200)),
            ],
        ),
    ]
